name: MinecraftCustomMaps
version: '${project.version}'
main: me.matistan05.minecraftcustommaps.Main
api-version: 1.16
commands:
  custommap:
    description: custom map
permissions:
    custommaps.custommap:
        description: Allows the player to use all /custommap commands
        children:
          custommaps.give: true
          custommaps.fillitemframes: true
          custommaps.changeproperties: true
          custommaps.geturl: true
          custommaps.fix: true
          custommaps.help: true

